---

- name: enable and start wg0
  become: yes
  ansible.builtin.systemd:
    name: wg-quick@wg0.service
    enabled: yes
    state: started
  when: install.wireguard_peerA is defined

- name: enable IP forwarding
  become: yes
  ansible.builtin.copy:
    src: wireguard/sysctl.d/
    dest: /etc/sysctl.d/
  when: install.wireguard_peerA is defined

- name: disable NetworManager for wg0
  become: yes
  ansible.builtin.copy:
    src: wireguard/NetworkManager/
    dest: /etc/NetworkManager/conf.d/
  when: install.wireguard_peer is defined