---

- name: enable flexo
  become: yes
  ansible.builtin.systemd:
    name: flexo
    enabled: yes

- name: start flexo
  become: yes
  ansible.builtin.systemd:
    name: flexo
    state: started

- name: enable and start sched-paccache.timer
  become: yes
  ansible.builtin.systemd:
    name: sched-paccache.timer
    enabled: yes
    state: started