---

- name: enable and start flexo
  ansible.builtin.systemd:
    name: flexo
    enabled: yes
    state: started

- name: enable and start sched-paccache.timer
  ansible.builtin.systemd:
    name: sched-paccache.timer
    enabled: yes
    state: started