cpu: intel

kernel:
  params: "mem_sleep_default=deep"
  modules: "vmd i915"

fonts:
  vconsole: ter-i18n

modules:
  blacklist:
    - "blacklist pcspkr"
  options:
    - "options i915 enable_guc=2"
    - "options iwlwifi power_save=1"
    - "options iwlmvm power_scheme=3"

env_vars:
  - "LIBVA_DRIVER_NAME=iHD"
  - "CLUTTER_BACKEND=wayland"
  - "QT_QPA_PLATFORM=wayland"
  - "SDL_VIDEODRIVER=wayland"
  - "MOZ_ENABLE_WAYLAND=1"

install:
  sudo:
  sysctl:
  udev:
  resolved:
  suspend:
  dotfiles:
  sshd:
  ssh_config:
  wireguard:
  gnome:
  nextdns_client:
  extra_packages:
  flatpak_packages:

extra_packages:
  - acpi_call
  - flatpak
  - gst-libav
  - intel-media-driver
  - vulkan-intel
  - libva-utils