cpu: intel

kernel:
  params: "mem_sleep_default=deep"
  modules: 
    install: "vmd i915"
    blacklist:
      - "blacklist pcspkr"
    options:
      - "options i915 enable_guc=2"
      - "options iwlwifi power_save=1"
      - "options iwlmvm power_scheme=3"

fonts:
  vconsole: ter-i18n

env_vars:
  - "LIBVA_DRIVER_NAME=iHD"
  - "CLUTTER_BACKEND=wayland"
  - "QT_QPA_PLATFORM=wayland"
  - "SDL_VIDEODRIVER=wayland"
  - "MOZ_ENABLE_WAYLAND=1"

install:
  dotfiles:
  extra_packages:
  flatpak_packages:
  git:
  gnome:
  nextdns_client:
  resolved:
  ssh_config:
  sudo:
  suspend:
  sysctl:
  udev:
  vconsole:
  wireguard_peer:

extra_packages:
  - acpi_call
  - flatpak
  - gst-libav
  - intel-media-driver
  - libva-utils
  - vulkan-intel