cpu: intel

kernel:
  params: "acpi_os_name=\"Windows 2015\" msr.allow_writes=on intremap=no_x2apic_optout pci=realloc intel_iommu=off"
  modules: "i915 intel_lpss_pci thinkpad_acpi"

fonts:
  vconsole: ter-i18n

modules:
  blacklist:
    - "blacklist pcspkr"
    - "blacklist i2c_i801"
    - "blacklist snd_hda_intel"
    - "blacklist snd_soc_skl"
  options:
    - "options i915 enable_guc=-1"
    - "options iwlwifi power_save=1"
    - "options iwlmvm power_scheme=3"
    - "options thinkpad_acpi experimental=1"

env_vars:
  - "LIBVA_DRIVER_NAME=iHD"
  - "CLUTTER_BACKEND=wayland"
  - "QT_QPA_PLATFORM=wayland"
  - "SDL_VIDEODRIVER=wayland"
  - "MOZ_ENABLE_WAYLAND=1"

install:
  grub:
  power:
  sysctl:
  udev:
  resolved:
  dotfiles:
  ssh_config:
  wireguard:
  gnome:
  nextdns_client:
  flexo_client:
  extra_packages:
  flatpak_packages:

extra_packages:
  - acpi_call