cpu: intel
gpu: i915

kernel:
  params: "msr.allow_writes=on intremap=no_x2apic_optout pci=realloc intel_iommu=off"
  modules: "i915 intel_lpss_pci thinkpad_acpi"

modules:
  blacklist:
    - "blacklist ideapad_laptop"
    - "blacklist pcspkr"
    - "blacklist i2c_i801"
    - "blacklist snd_hda_intel"
    - "blacklist snd_soc_skl"
  options:
    - "options i915 enable_guc=-1"
    - "options iwlwifi power_save=1"
    - "options iwlmvm power_scheme=3"

install:
  grub:
  acpid:
  dotfiles:
  gnome:
  nextdns: