---

- name: enable acpid
  systemd:
    name: acpid
    enabled: yes

- name: start acpid
  systemd:
    name: acpid
    enabled: yes

- name: restart acpid
  systemd:
    name: acpid
    state: restarted