---

- name: install gnome packages
  pacman:
    name: "{{packages.pacman}}"
    state: present
    update_cache: yes
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2

- name: install gnome packages from aur
  become: yes
  command: "yay --batchinstall --answerclean n --answerdiff n --answeredit n --answerupgrade n --aur -S {{packages.aur}}"