---

- name: copy ssh config from a local SMB share
  become: yes
  ansible.builtin.command: "{{item}}"
  with_items:
    - mount -t cifs //{{ssh.backup_host}}/{{ssh.backup_share}} {{ssh.backup_mount_point}} -o "username={{ssh.backup_host_user}},password={{ssh_backup_host.pass}}"
    - rsync -a {{ssh.backup_mount_point}}/{{ssh.backup_path}}/ /home/{{user.name}}/.ssh/
    - umount {{ssh.backup_mount_point}}
    - chown -R {{user.name}}:{{user.name}} /hone/{{user.name}}/.ssh
    - bash -c "chmod 600 /home/{{user.name}}/.ssh/*"
    - bash -c "chmod 644 /home/{{user.name}}/.ssh/*.pub"
  when: install.ssh_config is defined

- name: copy ssh config to a local SMB share
  become: yes
  ansible.builtin.command: "{{item}}"
  with_items:
    - mount -t cifs //{{ssh.backup_host}}/{{ssh.backup_share}} {{ssh.backup_mount_point}} -o "username={{ssh.backup_host_user}},password={{ssh_backup_host.pass}}"
    - rsync -a /home/{{user.name}}/.ssh/ {{ssh.backup_mount_point}}/{{ssh.backup_path}}/
    - umount {{ssh.backup_mount_point}}
  tags:
    - never
    - backup