packages:
  gnome:
    pacman:
      - flatpak
      - gdm
      - networkmanager
      - ostree
      - pipewire
      - pipewire-pulse
      - realtime-privileges
      - gnome-backgrounds
      - gnome-calculator
      - gnome-characters
      - gnome-clocks
      - gnome-color-manager
      - gnome-control-center
      - gnome-disk-utility
      - gnome-keyring
      - gnome-logs
      - gnome-menus
      - gnome-screenshot
      - gnome-session
      - gnome-settings-daemon
      - gnome-shell
      - gnome-shell-extensions
      - gnome-software
      - gnome-software-packagekit-plugin
      - gnome-system-monitor
      - gnome-terminal
      - gnome-themes-extra
      - gnome-tweaks
      - gnome-usage
      - gnome-user-share
      - gnome-video-effects
      - gnome-weather
    aur: