---

- name: backup mkinitcpio.conf
  become: yes
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/mkinitcpio.conf
    dest: /etc/mkinitcpio.conf.ans
  when: kernel.modules.install is defined

- name: modify mkinitcpio.conf
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/mkinitcpio.conf
    regex: "{{item.from}}"
    line: "{{item.to}}"
  with_items:
    - {from: "MODULES=()", to: "MODULES=({{kernel.modules.install}})"}
  when: kernel.modules.install is defined
  notify:
    - generate initramfs