---

- name: create modprobe.d/blacklist.conf
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{item}}"
  with_items:
    - "{{kernel.modules.blacklist}}"
  when: kernel.modules.blacklist is defined

- name: create modprobe.d/options.conf
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/options.conf
    line: "{{item}}"
  with_items:
    - "{{kernel.modules.options}}"
  when: kernel.modules.options is defined