---

- name: install acpid
  become: yes
  community.general.pacman:
    name: "acpid"
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2
  notify:
    - enable acpid
    - start acpid

