---

- name: run pacman -Sy
  pacman:
    update_cache: yes
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2

- name: run pacman -Syu
  pacman:
    update_cache: yes
    upgrade: yes
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2