---

- name: install gnome packages
  become: yes
  community.general.pacman:
    name: "{{packages.gnome.pacman}}"
    state: present
    update_cache: yes
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2

- name: install gnome packages from aur
  ansible.builtin.command: "{{aur.yay_cmd}} -S {{packages.gnome.aur}}"