---

- name: install gnome packages
  community.general.pacman:
    name: "{{packages.gnome.pacman}}"
    state: present
    update_cache: yes
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2

- name: install gnome packages from aur
  ansible.builtin.command: "yay --batchinstall --answerclean n --answerdiff n --answeredit n --answerupgrade n --aur -S {{packages.gnome.aur}}"