---

- name: enable GDM
  ansible.builtin.systemd:
    name: gdm
    enabled: yes

- name: enable and start NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: yes
    state: started