---

- name: enable GDM
  become: yes
  ansible.builtin.systemd:
    name: gdm
    enabled: yes

- name: enable and start NetworkManager
  become: yes
  ansible.builtin.systemd:
    name: NetworkManager
    state: started
    enabled: yes