---

- name: configure git
  ansible.builtin.command: git config --global {{item}}
  with_items:
    - user.name {{user.name}}
    - user.email {{user.email}}

- name: git integration with gnome-keyring
  ansible.builtin.command: git config --global credential.helper /usr/lib/git-core/git-credential-libsecret
  when: install.gnome is defined