---

- name: config flexo client
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    insertbefore: "^{{item.before}}$"
    line: "{{item.insert}}"
  with_items:
    - {before: "Include = /etc/pacman.d/mirrorlist", insert: "Server = http://{{flexo.server}}:7878/$repo/os/$arch"}
    - {before: "#Include = /etc/pacman.d/mirrorlist", insert: "#Server = http://{{flexo.server}}:7878/$repo/os/$arch"}