---

- import_tasks: config.yml
- import_tasks: yay.yml

- name: update packages with pacman
  become: yes
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  tags:
    - never
    - update_packages

- name: update AUR packages with yay
  ansible.builtin.command: "{{aur.yay_cmd}} -Syu"
  tags: 
    - never
    - update_packages