---

- import_tasks: config.yml
- import_tasks: yay.yml

- name: run pacman -Syu
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  tags:
    - never
    - pacman

- name: run yay -Syu
  become: yes
  ansible.builtin.command: "yay --answerclean n --answerdiff n --answeredit n --answerupgrade n -Syu"
  tags: 
    - never
    - yay