---

- import_tasks: config.yml
- import_tasks: yay.yml

- name: update packages with pacman
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  tags:
    - never
    - update_packages

- name: update AUR packages with yay
  ansible.builtin.command: "yay --answerclean n --answerdiff n --answeredit n --answerupgrade n --aur -Syu"
  tags: 
    - never
    - update_packages