---

- name: clone the yay repo
  ansible.builtin.git:
    repo: "{{aur.yay_repo}}"
    dest: "{{aur.yay_dest}}"

# - name: check that {{aur.yay_dest}} exists
#   ansible.builtin.stat:
#     path: "{{aur.yay_dest}}"
#   register: yay_dir

# - name: build and install yay
#   ansible.builtin.shell: 
#     cmd: "yes | makepkg -si"
#     chdir: "{{aur.yay_dest}}"
#   when: yay_dir.stat.isdir is defined and yay_dir.stat.isdir