packages:
  base:
    - base-devel
    - bash-completion
    - bc
    - coreutils
    - curl
    - dateutils
    - exa
    - fish
    - git
    - htop
    - lsof
    - neovim
    - netcat
    - nmap
    - openssh
    - pacman-contrib
    - python
    - rsync
    - strace      
    - terminus-font
    - tmux
    - vim
    
  flatpak:
    - com.discordapp.Discord
    - com.obsproject.Studio
    - com.slack.Slack
    - com.valvesoftware.Steam
    - com.valvesoftware.Steam.Utility.protontricks
    - org.audacityteam.Audacity
    - org.darktable.Darktable
    - org.gimp.GIMP
    - org.gnome.Boxes
    - org.signal.Signal
    - org.videolan.VLC
    - us.zoom.Zoom