---

- name: setup nextdns client
  become: yes
  ansible.builtin.command: "nextdns install -config {{nextdns.id}} -report-client-info -auto-activate"

- name: configure nextdns client
  become: yes
  ansible.builtin.command: "nextdns config set -cache-size=10MB -max-ttl=5s"
  notify: restart nextdns