---

- name: install systemd-resolvconf
  community.general.pacman:
    name: systemd-resolvconf
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2

- name: configure nextdns client
  become: yes
  ansible.builtin.template:
    src: 20-nextdns.conf.j2
    dest: /etc/systemd/resolved.conf.d/
  notify:
    - restart systemd-resolved