---

- name: install nextdns from aur
  ansible.builtin.command: "{{aur.yay_cmd}} -S nextdns"

- import_tasks: client.yml
  when: services.nextdns_client is defined

- import_tasks: server.yml
  when: services.nextdns_server is defined