---

- name: install base packages
  become: yes
  community.general.pacman:
    update_cache: yes
    name: "{{packages.base}}"
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2

- name: install extra packages
  become: yes
  community.general.pacman:
    name: "{{extra_packages}}"
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2
  when: install.extra_packages is defined

- name: add flathub repo
  become: yes
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  when: install.flatpak_packages is defined

- name: install flatpak packages
  become: yes
  ansible.builtin.command: flatpak install -y {{packages.flatpak}}
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2
  when: install.flatpak_packages is defined