---

- name: disable mdns in systemd-resolved
  become: yes
  ansible.builtin.copy:
    src: resolved/
    dest: /etc/systemd/resolved.conf.d/
  when:
    - install.resolved is defined
  notify:
    - restart systemd-resolved