---

- name: sysctl config
  become: yes
  ansible.builtin.copy:
    src: "{{item}}"
    dest: /etc/systctl.d/
  loop:
    - 99-swappiness.conf
    - dirty.conf
    - disable_watchdog.conf
  where: install.sysctl is defined