---

- name: archlinux initial setup
  hosts: archlinux

  roles:
    - { role: roles/setup }
    - { role: roles/kernel }
    - { role: roles/pacman }
    - { role: roles/resolved }
    - { role: roles/grub, when: install.grub is defined }
    - { role: roles/acpid, when: "install.acpid is defined" }    
    - { role: roles/dotfiles, when: "install.dotfiles is defined" }
    - { role: roles/gnome, when: "install.gnome is defined" }