---

- name: archlinux initial setup
  hosts: archlinux
  become: yes

  roles:
    - { role: ../roles/archlinux/setup }
    - { role: ../roles/archlinux/kernel }
    - { role: ../roles/archlinux/pacman }
    - { role: ../roles/archlinux/grub, when: install.grub is defined }
    - { role: ../roles/archlinux/acpid, when: "install.acpid is defined" }    
    - { role: ../roles/archlinux/nextdns, when: "install.nextdns is defined" }
    - { role: ../roles/archlinux/dotfiles, when: "install.dotfiles is defined" }
    - { role: ../roles/archlinux/gnome, when: "install.gnome is defined" }