---

- name: archlinux initial setup
  hosts: archlinux

  roles:
    - role: roles/setup
    - role: roles/kernel
    - role: roles/pacman

    - role: roles/grub
      when: install.grub is defined

    - role: roles/acpid
      when: install.acpid is defined

    - role: roles/power
      when: install.power is defined

    - role: roles/git

    - role: roles/nextdns

    - role: roles/flexo

    - role: roles/wireguard
      when: install.wireguard is defined

    - role: roles/dotfiles
      when: install.dotfiles is defined

    - role: roles/backup

    - role: roles/gnome
      when: install.gnome is defined