---

- name: archlinux initial setup
  hosts: archlinux

  roles:
    - role: roles/microcode
      when: cpu is defined

    - role: roles/udev
      when: install.udev is defined

    - role: roles/resolved
      when: install.resolved is defined

    - role: roles/sysctl
      when: install.sysctl is defined

    - role: roles/sudo
      when: install.sudo is defined

    - role: roles/sshd
      when: install.sshd is defined

    - role: roles/suspend
      when: install.suspend is defined

    - role: roles/environment
      when: env_vars is defined

    - role: roles/vconsole
      when: fonts.vconsole is defined

    - role: roles/packages

    - role: roles/kernel
    - role: roles/pacman

    - role: roles/nextdns

    - role: roles/flexo

    - role: roles/wireguard
      when: install.wireguard is defined

    - role: roles/dotfiles
      when: install.dotfiles is defined

    - role: roles/gnome
      when: install.gnome is defined

    - role: roles/git
