---

- name: archlinux initial setup
  hosts: archlinux
  become: yes

  roles:
    - { role: ../roles/archlinux/setup }
    - { role: ../roles/archlinux/kernel }
    - { role: ../roles/archlinux/acpid, when: "'ultraviolet' in inventory_hostname" }    
    - { role: ../roles/archlinux/pacman }
    - { role: ../roles/archlinux/nextdns, when: "'ultraviolet' in inventory_hostname" }
    - { role: ../roles/archlinux/dotfiles }