---

- name: install {{cpu}}-ucode and update grub
  pacman:
    name: "{{cpu}}-ucode"
  when: cpu is defined
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2
  notify:
    - update grub
