---

- name: install openssh package
  become: yes
  community.general.pacman:
    update_cache: yes
    name: openssh
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2
  notify: enable and start sshd
